@echo off
cd /d "C:\Users\Hugo Pendziuch\Documents\claude\SerTecApp\sertecapp-worker"
echo [1/11] roles...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_roles.sql 2>&1 | findstr "executed error"
echo [2/11] users...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_users.sql 2>&1 | findstr "executed error"
echo [3/11] user_roles...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_user_roles.sql 2>&1 | findstr "executed error"
echo [4/11] customers...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_customers.sql 2>&1 | findstr "executed error"
echo [5/11] equipment_brands...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_equipment_brands.sql 2>&1 | findstr "executed error"
echo [6/11] equipment_models...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_equipment_models.sql 2>&1 | findstr "executed error"
echo [7/11] equipments...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_equipments.sql 2>&1 | findstr "executed error"
echo [8/11] parts...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_parts.sql 2>&1 | findstr "executed error"
echo [9/11] work_orders...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_work_orders.sql 2>&1 | findstr "executed error"
echo [10/11] wo_parts_used...
npx wrangler d1 execute sertecapp-db --remote --file=scripts/import_wo_parts_used.sql 2>&1 | findstr "executed error"
echo [11/11] Verificando...
npx wrangler d1 execute sertecapp-db --remote --command="SELECT 'customers' as t, COUNT(*) as n FROM customers UNION ALL SELECT 'parts', COUNT(*) FROM parts UNION ALL SELECT 'users', COUNT(*) FROM users UNION ALL SELECT 'work_orders', COUNT(*) FROM work_orders" 2>&1 | findstr /i "customers parts users work_orders"
echo MIGRACION REMOTA COMPLETA
pause
